dataset:
  dataset_name: "ShenRuililin/MedicalQnA"
  dataset_percentage: 1.0 # all the data for final training
  hyperparameter_search_percentage: 0.3 # 30% of the data for hyperparameter search
model:
  model_name: "distilbert/distilgpt2"

model_optimization:
  quantization:
    load_in_4bit: true
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true
  lora:
    r: 8
    lora_alpha: 32
    lora_dropout: 0.1
    target_modules: []
